# Generated by Django 3.2.6 on 2022-04-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passworld', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
