# Generated by Django 3.2.6 on 2022-04-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labrary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userinfo',
            new_name='Admininfo',
        ),
        migrations.AlterModelTable(
            name='admininfo',
            table='Admininfo',
        ),
    ]
