# Generated by Django 3.2.6 on 2022-04-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labrary', '0002_auto_20220406_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
