# Generated by Django 3.2.6 on 2022-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labrary', '0003_alter_admininfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('price', models.FloatField(default=200)),
            ],
        ),
    ]
